export const menuData = [
    // Appetizers
    { itemName: "Spring Rolls", price: 120, course: "appetizers" },
    { itemName: "Veg Manchurian", price: 150, course: "appetizers" },
    { itemName: "Paneer Tikka", price: 180, course: "appetizers" },
    { itemName: "Veg Noodles", price: 130, course: "appetizers" },
    { itemName: "Veg Fried Rice", price: 140, course: "appetizers" },
    { itemName: "Veg Biryani", price: 160, course: "appetizers" },
    { itemName: "Veg Pulao", price: 150, course: "appetizers" },
    { itemName: "Veg Curry", price: 170, course: "appetizers" },
    { itemName: "Veg Korma", price: 180, course: "appetizers" },
    { itemName: "Veg Masala", price: 160, course: "appetizers" },
    { itemName: "Veg Tikka", price: 170, course: "appetizers" },
    { itemName: "Veg Pakora", price: 120, course: "appetizers" },
    { itemName: "Veg Samosa", price: 100, course: "appetizers" },
    { itemName: "Veg Cutlet", price: 130, course: "appetizers" },
    { itemName: "Veg Spring Roll", price: 140, course: "appetizers" },
    { itemName: "Veg Momos", price: 150, course: "appetizers" },
    { itemName: "Veg Dim Sum", price: 160, course: "appetizers" },
    { itemName: "Veg Wonton", price: 140, course: "appetizers" },
    { itemName: "Veg Dumpling", price: 150, course: "appetizers" },
    { itemName: "Veg Roll", price: 130, course: "appetizers" },
    { itemName: "Veg Wrap", price: 140, course: "appetizers" },
    { itemName: "Veg Sandwich", price: 120, course: "appetizers" },
    { itemName: "Veg Burger", price: 130, course: "appetizers" },
    { itemName: "Veg Pizza", price: 160, course: "appetizers" },
    { itemName: "Veg Pasta", price: 150, course: "appetizers" },
    { itemName: "Veg Macaroni", price: 140, course: "appetizers" },
    { itemName: "Veg Spaghetti", price: 150, course: "appetizers" },
    { itemName: "Veg Lasagna", price: 170, course: "appetizers" },
    { itemName: "Veg Ravioli", price: 160, course: "appetizers" },
    { itemName: "Veg Cannelloni", price: 170, course: "appetizers" },

    // Main Course
    { itemName: "Butter Chicken", price: 250, course: "main course" },
    { itemName: "Chicken Tikka Masala", price: 280, course: "main course" },
    { itemName: "Chicken Biryani", price: 220, course: "main course" },
    { itemName: "Chicken Curry", price: 200, course: "main course" },
    { itemName: "Chicken Korma", price: 230, course: "main course" },
    { itemName: "Chicken Masala", price: 210, course: "main course" },
    { itemName: "Chicken Tikka", price: 240, course: "main course" },
    { itemName: "Chicken Pakora", price: 180, course: "main course" },
    { itemName: "Chicken Samosa", price: 160, course: "main course" },
    { itemName: "Chicken Cutlet", price: 190, course: "main course" },
    { itemName: "Chicken Spring Roll", price: 200, course: "main course" },
    { itemName: "Chicken Momos", price: 210, course: "main course" },
    { itemName: "Chicken Dim Sum", price: 220, course: "main course" },
    { itemName: "Chicken Wonton", price: 200, course: "main course" },
    { itemName: "Chicken Dumpling", price: 210, course: "main course" },
    { itemName: "Chicken Roll", price: 190, course: "main course" },
    { itemName: "Chicken Wrap", price: 200, course: "main course" },
    { itemName: "Chicken Sandwich", price: 180, course: "main course" },
    { itemName: "Chicken Burger", price: 190, course: "main course" },
    { itemName: "Chicken Pizza", price: 220, course: "main course" },
    { itemName: "Chicken Pasta", price: 210, course: "main course" },
    { itemName: "Chicken Macaroni", price: 200, course: "main course" },
    { itemName: "Chicken Spaghetti", price: 210, course: "main course" },
    { itemName: "Chicken Lasagna", price: 230, course: "main course" },
    { itemName: "Chicken Ravioli", price: 220, course: "main course" },
    { itemName: "Chicken Cannelloni", price: 230, course: "main course" },

    // Breads
    { itemName: "Naan", price: 30, course: "breads" },
    { itemName: "Butter Naan", price: 40, course: "breads" },
    { itemName: "Garlic Naan", price: 50, course: "breads" },
    { itemName: "Cheese Naan", price: 60, course: "breads" },
    { itemName: "Tandoori Roti", price: 30, course: "breads" },
    { itemName: "Butter Roti", price: 40, course: "breads" },
    { itemName: "Missi Roti", price: 50, course: "breads" },
    { itemName: "Aloo Paratha", price: 60, course: "breads" },
    { itemName: "Paneer Paratha", price: 70, course: "breads" },
    { itemName: "Laccha Paratha", price: 50, course: "breads" },
    { itemName: "Roomali Roti", price: 40, course: "breads" },
    { itemName: "Kulcha", price: 50, course: "breads" },
    { itemName: "Bhatura", price: 60, course: "breads" },
    { itemName: "Poori", price: 40, course: "breads" },
    { itemName: "Chapati", price: 30, course: "breads" },

    // Desserts
    { itemName: "Gulab Jamun", price: 80, course: "desserts" },
    { itemName: "Rasgulla", price: 80, course: "desserts" },
    { itemName: "Rasmalai", price: 100, course: "desserts" },
    { itemName: "Kheer", price: 90, course: "desserts" },
    { itemName: "Ice Cream", price: 70, course: "desserts" },
    { itemName: "Kulfi", price: 60, course: "desserts" },
    { itemName: "Jalebi", price: 50, course: "desserts" },
    { itemName: "Rabri", price: 90, course: "desserts" },
    { itemName: "Shahi Tukda", price: 100, course: "desserts" },
    { itemName: "Phirni", price: 80, course: "desserts" },
    { itemName: "Gajar Halwa", price: 90, course: "desserts" },
    { itemName: "Moong Dal Halwa", price: 100, course: "desserts" },
    { itemName: "Besan Ladoo", price: 70, course: "desserts" },
    { itemName: "Coconut Ladoo", price: 80, course: "desserts" },
    { itemName: "Kaju Katli", price: 120, course: "desserts" },

    // Beverages
    { itemName: "Masala Chai", price: 30, course: "beverages" },
    { itemName: "Coffee", price: 40, course: "beverages" },
    { itemName: "Lassi", price: 50, course: "beverages" },
    { itemName: "Mango Lassi", price: 60, course: "beverages" },
    { itemName: "Buttermilk", price: 40, course: "beverages" },
    { itemName: "Lemonade", price: 50, course: "beverages" },
    { itemName: "Mojito", price: 60, course: "beverages" },
    { itemName: "Fresh Juice", price: 70, course: "beverages" },
    { itemName: "Soda", price: 30, course: "beverages" },
    { itemName: "Mineral Water", price: 20, course: "beverages" },
    { itemName: "Soft Drinks", price: 40, course: "beverages" },
    { itemName: "Milkshake", price: 80, course: "beverages" },
    { itemName: "Smoothie", price: 90, course: "beverages" },
    { itemName: "Hot Chocolate", price: 70, course: "beverages" },
    { itemName: "Green Tea", price: 40, course: "beverages" }
]; 